"""empty message

Revision ID: 2c7f9a14a16b
Revises: 
Create Date: 2023-11-24 20:37:43.336957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c7f9a14a16b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kredi',
    sa.Column('kredi_durum', sa.String(), nullable=True),
    sa.Column('kredi_musteri_id', sa.Integer(), nullable=False),
    sa.Column('kredi_faiz_orani', sa.Float(), nullable=False),
    sa.Column('kredi_son_tarih', sa.DateTime(), nullable=False),
    sa.Column('kredi_tutar', sa.Float(), nullable=False),
    sa.Column('kredi_ay', sa.Integer(), nullable=True),
    sa.Column('kredi_geri_odeme', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kredi_musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('manav')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manav',
    sa.Column('manav_adi', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('manav_adresi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manav_tel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manav_custom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('guncellenme_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='manav_pkey')
    )
    op.drop_table('kredi')
    # ### end Alembic commands ###
