"""empty message

Revision ID: 45d375fca9af
Revises: fc5b5c1a7581
Create Date: 2023-12-16 12:42:15.965331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d375fca9af'
down_revision = 'fc5b5c1a7581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.alter_column('fatura_durum',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.alter_column('fatura_durum',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
