"""empty message

Revision ID: 540292b2df1a
Revises: 531123980110
Create Date: 2023-12-12 14:45:08.030663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540292b2df1a'
down_revision = '531123980110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hesap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hesap_AcanSube', sa.String(), nullable=False, foreign_keys='sube.id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hesap', schema=None) as batch_op:
        batch_op.drop_column('hesap_AcanSube')

    # ### end Alembic commands ###
