"""empty message

Revision ID: 54e21227f18f
Revises: 15c39888205f
Create Date: 2023-12-16 12:16:44.844558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e21227f18f'
down_revision = '15c39888205f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatura_durum', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_column('fatura_durum')

    # ### end Alembic commands ###
