"""empty message

Revision ID: 5b3cc3cb7750
Revises: d92d7e887827
Create Date: 2023-12-11 17:46:06.059769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3cc3cb7750'
down_revision = 'd92d7e887827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hesap', schema=None) as batch_op:
        batch_op.drop_column('hesap_Aciklama')
        batch_op.drop_column('hesap_HesapNo')
        batch_op.drop_column('hesap_AcilisTarih')

    with op.batch_alter_table('hesapHaraket', schema=None) as batch_op:
        batch_op.drop_column('haraketTarih')
        batch_op.drop_column('hareketAciklama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hesapHaraket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hareketAciklama', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('haraketTarih', sa.VARCHAR(), autoincrement=False, nullable=False))

    with op.batch_alter_table('hesap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hesap_AcilisTarih', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hesap_HesapNo', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hesap_Aciklama', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
