"""empty message

Revision ID: c77d0d034e61
Revises: 540292b2df1a
Create Date: 2023-12-12 14:45:53.746921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77d0d034e61'
down_revision = '540292b2df1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hesap', schema=None) as batch_op:
        batch_op.alter_column('hesap_AcanSube',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sube', ['hesap_AcanSube'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hesap', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('hesap_AcanSube',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
