"""empty message

Revision ID: c7bfd4499231
Revises: da272474313f
Create Date: 2023-12-12 18:17:34.311066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bfd4499231'
down_revision = 'da272474313f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hesap',
    sa.Column('hesap_AcanSube', sa.Integer(), nullable=False),
    sa.Column('hesap_ParaBirim', sa.String(), nullable=False),
    sa.Column('hesap_bakiye', sa.Float(), nullable=True),
    sa.Column('hesap_musteri_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hesap_AcanSube'], ['sube.id'], ),
    sa.ForeignKeyConstraint(['hesap_musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kredi',
    sa.Column('kredi_durum', sa.String(), nullable=True),
    sa.Column('kredi_hesap_id', sa.Integer(), nullable=False),
    sa.Column('kredi_faiz_orani', sa.Float(), nullable=False),
    sa.Column('kredi_son_tarih', sa.DateTime(), nullable=False),
    sa.Column('kredi_tutar', sa.Float(), nullable=False),
    sa.Column('kredi_ay', sa.Integer(), nullable=True),
    sa.Column('kredi_geri_odeme', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kredi_hesap_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatura',
    sa.Column('fatura_musteri_id', sa.Integer(), nullable=False),
    sa.Column('fatura_hesap_id', sa.Integer(), nullable=False),
    sa.Column('fatura_miktar', sa.Float(), nullable=False),
    sa.Column('fatura_turu', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fatura_hesap_id'], ['hesap.id'], ),
    sa.ForeignKeyConstraint(['fatura_musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hesapHaraket',
    sa.Column('hareket_hesap_id', sa.Integer(), nullable=False),
    sa.Column('hareketMiktar', sa.String(), nullable=False),
    sa.Column('hareket_turu', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hareket_hesap_id'], ['hesap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hesapHaraket')
    op.drop_table('fatura')
    op.drop_table('kredi')
    op.drop_table('hesap')
    # ### end Alembic commands ###
