"""empty message

Revision ID: da272474313f
Revises: 19f23dc90489
Create Date: 2023-12-12 15:43:56.119837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da272474313f'
down_revision = '19f23dc90489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatura_turu', sa.String(), nullable=False))
        batch_op.drop_column('fatura_türü')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatura_türü', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('fatura_turu')

    # ### end Alembic commands ###
