"""empty message

Revision ID: fc5b5c1a7581
Revises: 54e21227f18f
Create Date: 2023-12-16 12:19:10.938534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5b5c1a7581'
down_revision = '54e21227f18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_constraint('fatura_fatura_hesap_id_fkey', type_='foreignkey')
        batch_op.drop_column('fatura_hesap_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatura_hesap_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fatura_fatura_hesap_id_fkey', 'hesap', ['fatura_hesap_id'], ['id'])

    # ### end Alembic commands ###
